"use strict";

/* =====================================================================
   2. LANGUAGE
   ===================================================================== */

const T={
sv:{
  word:"Kurvan", sub:"Psykisk hälsa i Sverige",
  tabs:{laget:"Läget",over_tid:"Över tid",karta:"Karta",behov:"Behov & vård",sjukskrivning:"Sjukskrivning",kon:"Jämförelse efter kön",sammanhang:"Sammanhang",metod:"Metod",regioner:"Regioner"},
  comingT:"Under uppbyggnad",
  comingB:"Den här sidan är beskriven i observatoriets plan men inte byggd än i den här prototypen.",
  ctxLead:"Befolknings- och samhällsdata vid sidan av de psykiska hälsomåtten — inte sammanslaget till ett mått. Ett samband här visar inte orsak.",
  ctxInd:{pop_density:"Invånare per kvadratkilometer",education_low_pct:"Andel med låg utbildningsnivå"},
  ctxCaveat:"Regionens värde är ett ovägt medelvärde av dess kommuner, inte befolkningsviktat. Källa: Kolada, 2023.",
  legendRankNote:"Regionerna delas in i fem lika stora grupper efter värde — inte jämnstora intervall.",
  legendTiers:["Lägst","Lägre","Mitten","Högre","Högst"],
  langBtn:"EN", themeD:"Mörkt", themeL:"Ljust",
  stamp:"Data t.o.m. 2024 · uppdaterad aug 2026",
  synthT:"Syntetiska data", synthB:"Alla siffror på den här sidan är genererade. Panelen innehåller ingen verklig statistik.",
  synthPartialT:"Mestadels verkliga data",
  // Computed from IND/isRealActive() via realSummary() (views.js), not
  // hand-counted — see synthPartialB's English twin for why.
  synthPartialB:(n,total,realNames,synthNames,synthN)=>`${n} av ${total} indikatorer bygger nu på verklig, öppen statistik: ${realNames}. Bara ${synthNames} är fortfarande genererad${synthN>1?"e":""} — se märkningen vid varje diagram.`,
  realLbl:"verkliga data", synthLbl:"syntetiska data",
  realCaveat:{
    selfharm:"Verkliga siffror gäller endast 12–17 år, totalt kön, femårsfönster.",
    suicide:"Verkliga siffror gäller endast 15–19 år, totalt kön, femårsfönster.",
    psych:"Alla F00–F99-diagnoser samlat, årsvis, alla åldrar och kön — men bara specialistvård.",
    distress:"Ingen åldersuppdelning finns i källan; \"Alla åldrar\" är enda valet. Bytte namn från \"Nedsatt psykiskt välbefinnande\" — den kategorin slutade publiceras efter 2015–2018.",
    sjukfranvaro:"Verkliga siffror gäller 2005–2019 (källan slutar där, täcker inte 2020-talet). Ingen åldersuppdelning."
  },
  realNoteL:"Vad som faktiskt är verkligt här",
  // realNames leads the sentence here (unlike synthPartialB/footBPartial,
  // where it follows a colon) — capitalise just its first letter back up.
  realNoteOn:(n,total,realNames,synthNames,synthN)=>`${realNames.charAt(0).toUpperCase()+realNames.slice(1)} är nu verklig, öppen statistik, hämtad av prototype/pipeline/. Bara ${synthNames} saknar hämtskript i det här projektet och förblir genererad${synthN>1?"e":""} — se märkningen vid varje diagram.`,
  realNoteOff:"Ingen indikator är verklig data ännu på den här sidan. prototype/pipeline/ kan hämta verkliga siffror för svår ängslan/oro, psykiatrisk specialistvård, självskada och suicid; kör fetcherna och sedan build_kurvan_data.py för att aktivera dem.",
  legend:[["survey","Enkäten","frågar människor direkt"],["reg","Registren","räknar dem som nått vården"],["mort","Dödsorsaksregistret","missar ingen"]],
  kick:"Veckans bild",
  h1:"Den ålder som skadar sig själv är inte den ålder som dör",
  hp:"Slutenvård för självskada toppar före 25 och är vanligast bland unga kvinnor. Suicid stiger genom hela livet och är vanligast bland de äldsta männen. Nästan all uppmärksamhet ligger på den första kurvan.",
  twinT:"Två kurvor, samma befolkning",
  shTitle:"Slutenvårdad för självskada", suTitle:"Avlidna i suicid",
  perK:"per 100 000 · 2024", women:"kvinnor", men:"män",
  peakSh:"kvinnor 15–24", peakSu:"män 85+",
  gapTitle:"Rapporterat behov mot vårdrespons",
  gapUnit:"21 regioner · vuxna · 2024 · två oberoende instrument",
  gapX:"uppger svår ängslan, oro eller ångest, % (enkät)",
  gapY:"uthämtade antidepressiva, per 1 000 (register)",
  gapLine:"genomsnittligt samband mellan behov och respons",
  causalNote:"Ett samband är inte en orsak. Regioner skiljer sig åt av många skäl som den här grafen inte visar.",
  gapPiece:{tag:"Behov och respons",inst:"reg",h:"Störst avstånd mellan behov och respons",p:"Regionen med störst skillnad mellan rapporterat behov och registrerad vårdrespons, 2024.",numl:"störst avstånd 2024"},
  pieces:[
    {tag:"Livsloppet",inst:"mort",h:"De äldsta männen",p:"Suicidtalet bland män 85+ är landets högsta. Enkäten slutar vid 84, så gruppen syns inte i något mått på självrapporterad ohälsa.",numl:"per 100 000 · män 85+"},
    {tag:"Förskrivning",inst:"reg",h:"Unga kvinnor, 20 år av ökning",p:"Uthämtade antidepressiva bland kvinnor 15–24 sedan registret startade 2006.",numl:"2006 → 2024 · kvinnor 15–24"}
  ],
  ind:{distress:"Svår ängslan, oro eller ångest",antidep:"Uthämtade antidepressiva",psych:"Psykiatrisk specialistvård",selfharm:"Slutenvårdad för självskada",suicide:"Avlidna i suicid",sjukfranvaro:"Sjukskrivning, stressreaktion (F43)"},
  fkLead:"Andel pågående sjukfall med diagnosen stressreaktion (F43) — ett mått på samhällelig/funktionell påverkan, inte ett direkt mått på psykisk ohälsa och inte en kostnadsberäkning.",
  konLead:"Svår ängslan/oro, psykiatrisk specialistvård och sjukskrivning publiceras alla uppdelat på kön i sina källor — här jämförs kvinnor och män över tid för respektive mått, rikssiffror.",
  konCaveat:"Slutenvårdad för självskada och avliden i suicid saknas här: de källorna publicerar bara totalt kön, ingen verklig uppdelning på kvinnor/män finns att visa.",
  lblInd:"Indikator",lblAge:"Åldersgrupp",lblSex:"Kön",lblYear:"År",lblReg:"Region",
  allAges:"Alla åldrar",sexT:"Totalt",sexM:"Män",sexK:"Kvinnor",
  crude:"Ojusterat",std:"Åldersstandardiserat",
  dotTitle:"Alla 21 regioner",dotSub:"Sorterat · 95 % konfidensintervall. Överlappande intervall är ingen rangordning.",
  ageTitle:"Genom livet",ageSub:"mot rikets band",
  timeTitle:"Över tid",
  natLine:"Riket",
  winLbl:y=>`${y-2}–${y+2}`,   // y is the window's MIDPOINT (matches midpoint_year everywhere real data is keyed), not its end. No "fönster"/"window" prefix — the dash range already reads as a period, and the Over time tab's own year dropdown shows the same range unprefixed.
  suppLbl:"Undertryckt, färre än 10 fall per fönster:",
  surveyEnd:"enkäten slutar vid 84",
  breakLbl:"nytt mått",
  pandemicLbl:"pandemi",
  spreadNote:(s,mode)=>`Spridningen mellan högsta och lägsta region är <b>${s} %</b> av rikets nivå. ${mode?"Byt till ojusterat och se hur mycket ålderstrukturen lägger till.":"Byt till åldersstandardiserat och se hur mycket som är ålderstruktur."}`,
  notNum:"Vad talet inte är.",
  notNumB:{
    antidep:"Räknar personer som hämtat ut ett recept, oavsett förskrivare. Ingen diagnos, och det stiger både när behandlingen förbättras och när hälsan försämras.",
    psych:"Räknar endast specialistvård. Det mesta av vanlig depression sköts i primärvården och syns inte här alls.",
    selfharm:"Räknar vårdtillfällen, inte personer. Y10–Y34 redovisas tillsammans med X60–X84 eftersom kodning av avsikt driver mellan regioner.",
    suicide:"Femårsfönster. Antal under 10 per fönster redovisas inte; talet publiceras ändå.",
    distress:"Självrapporterat, 16–84 år. Redovisas i fyraårsfönster (två sammanslagna enkätomgångar) för regional tillförlitlighet; ingen åldersuppdelning finns i regiontabellen.",
    sjukfranvaro:"Andel av pågående sjukfall, inte andel av befolkningen. Räknar sjukfall, inte personer med psykisk ohälsa i stort — och mäter inte behandling eller diagnos i vården."
  },
  dl:"Ladda ner serien",
  peers:"Jämförs med liknande regioner (ålderstruktur och inkomst):",
  rDistress:"Svår ängslan/oro",rTreated:"Behandlade",rSuicide:"Suicid",
  vsPeers:"Liknande regioner",notDiff:"Skillnaden går inte att skilja från noll.",
  higher:"Högre än liknande regioner.",lower:"Lägre än liknande regioner.",
  gapPos:"Regionens läge: behov mot vårdrespons",gapPosU:"avvikelse från genomsnittligt samband · 2024",
  scatterBelowKey:"Störst avstånd under sambandet",scatterAboveKey:"Störst avstånd över sambandet",
  behovLead:"Rapporterat behov jämfört med registrerad vårdrespons, region för region.",
  behovOpen:"Öppna Behov & vård →",
  changed:"Vad har rört sig",changedU:(a,b)=>`${a} → ${b} · förändring med intervall`,
  withinCI:"inom intervallet",
  chgNote:n=>`<b>${n} av 4 förändringar är inte förändringar.</b> De ligger inom intervallet och visas nedtonade.`,
  methodH:"Så är siffrorna framtagna",
  mIndicator:"Indikator",mSource:"Källa",mFrom:"Serie från",mGrain:"Nivå",mLimit:"Det viktigaste förbehållet",
  mRows:{
    distress:["Region, ~4-årsfönster","Endast 16–84 år. Ingen åldersuppdelning i regiontabellen; fönstren är ojämnt fördelade, inte en fast takt."],
    antidep:["Region","Registret startade juli 2005; helår från 2006. Uthämtning, inte diagnos."],
    psych:["Region","Endast specialistvård (SVOV-definitionen från 2008). Primärvård ingår inte."],
    selfharm:["Region","Från 2008. Vårdtillfällen, inte personer. Y10–Y34 följer med."],
    suicide:["Region, 5-årsfönster","Från 1997 nationellt; fönster från 2001. Antal <10 undertrycks."],
    sjukfranvaro:["Region","Från 2005, men källan slutar 2019 — täcker inte 2020-talet. Andel av pågående sjukfall med diagnos F43, inte en befolkningsandel."]
  },
  mProse:{
    a:"Tre instrument, inte ett",
    b:"Enkäten frågar människor direkt, registren räknar dem som nått vården, dödsorsaksregistret missar ingen. Instrumenten är blinda på olika ställen, och det är därför avståndet mellan dem betyder något. Ett konkret exempel: enkäten slutar vid 84 års ålder, och landets högsta suicidtal ligger bland män 85 och äldre. Gruppen med störst risk är osynlig i varje mått på självrapporterad ohälsa. Sjukskrivning läggs till som ett fjärde, annorlunda instrument: ett mått på samhällelig påverkan, inte på psykisk ohälsa i sig.",
    c:"Åldersstandardisering",
    d:"Regionernas åldersstruktur skiljer sig kraftigt. Ett ojusterat tal för något åldersberoende är till stor del en karta över åldersstruktur. Båda versionerna publiceras, med reglaget synligt.",
    e:"Osäkerhet och små tal",
    f:"Varje regionalt tal bär sitt 95-procentiga intervall. Suicid redovisas i femårsfönster på regionnivå, och fönster med färre än tio fall redovisas utan antal. Raden finns kvar: en saknad rad ser ut som saknade data, inte som en skyddad uppgift.",
    g:"Det här kan siffrorna inte säga",
    h:"Patientregistret innehåller endast specialistvård, så det mesta av vanlig depression saknas, och saknas olika mycket i olika regioner. Detta är områdesstatistik, inte utsagor om enskilda personer. Incidens går inte att räkna fram ur aggregerade data."
  },
  mapTitle:"Regionkarta",
  mapNote:(real)=>real
    ?"Färgstyrkan visar nivå för vald indikator. Kartan är verklig geografi — värdena är verkliga Socialstyrelsen-data också; se förbehållet nedan."
    :"Färgstyrkan visar nivå för vald indikator, 2024. Kartan är själva geografin — värdena är fortfarande syntetiska.",
  mapPicked:"vald region",mapOpen:"Öppna regionsidan",
  trendWith:"följer riket",trendAgainst:"mot rikets riktning",
  trendNote:(a,b)=>`Peka på en region för pil ↑/↓/→: förändring ${a}→${b} mot intervallet, och om den följer eller går mot rikets rörelse.`,
  cmpToggle:"⇄ Jämför två kartor",
  zoomIn:"Zooma in kartan",zoomOut:"Zooma ut kartan",
  histTitle:"Fördelning mellan regioner",
  histSub:"Antal regioner per nivåband. Visar spridningen, inte vilken region som är vilken.",
  histCount:"antal regioner",
  helpA:"Självmordslinjen 90101",helpB:"öppet dygnet runt, alla dagar",helpC:"1177 för vårdrådgivning",
  footA:"Utkast. Byggd på den öppna dataarkitektur som utvecklats för Svenska barnhälsoobservatoriet. Ett fristående projekt, inte knutet till barnhalsovard.se.",
  footB:"Varje siffra på den här sidan är genererad för att visa en design. Ingen är en mätning och ingen ska citeras. Källhänvisningarna beskriver var de riktiga serierna finns.",
  footBPartial:(n,total,realNames,synthNames,synthN)=>`${n} av ${total} indikatorer — ${realNames} — bygger nu på verklig, öppen statistik och kan citeras med respektive källhänvisning. Bara ${synthNames} är fortfarande genererad${synthN>1?"e":""} för att visa en design; den siffran är inte en mätning.`
},
en:{
  word:"Kurvan", sub:"Mental health in Sweden",
  tabs:{laget:"The picture",over_tid:"Over time",karta:"Map",behov:"Need & care",sjukskrivning:"Sickness absence",kon:"Comparison by sex",sammanhang:"Context",metod:"Method",regioner:"Regions"},
  comingT:"Under construction",
  comingB:"This page is described in the observatory's plan but not built yet in this prototype.",
  ctxLead:"Population and societal data alongside the mental-health measures — not merged into one score. A relationship shown here does not establish a cause.",
  ctxInd:{pop_density:"Residents per square kilometre",education_low_pct:"Share with low education level"},
  ctxCaveat:"A region's value is an unweighted mean of its municipalities, not population-weighted. Source: Kolada, 2023.",
  legendRankNote:"Regions are split into five equal-sized groups by value — not equal-width ranges.",
  legendTiers:["Lowest","Lower","Middle","Higher","Highest"],
  langBtn:"SV", themeD:"Dark", themeL:"Light",
  stamp:"Data to 2024 · updated Aug 2026",
  synthT:"Synthetic data", synthB:"Every figure on this page is generated. It contains no real statistics.",
  synthPartialT:"Mostly real data",
  // n/total/realNames/synthNames/synthN come from realSummary() (views.js),
  // computed from IND + isRealActive() on every render — so this sentence
  // can't quietly go stale the way a hand-typed "four of five" already did
  // once (it omitted sjukfranvaro after that indicator went real).
  synthPartialB:(n,total,realNames,synthNames,synthN)=>`${n} of ${total} indicators now draw on real, open statistics: ${realNames}. Only ${synthNames} ${synthN>1?"are":"is"} still generated — see the label on every chart.`,
  realLbl:"real data", synthLbl:"synthetic data",
  realCaveat:{
    selfharm:"Real figures cover ages 12–17 only, total sex, five-year windows.",
    suicide:"Real figures cover ages 15–19 only, total sex, five-year windows.",
    psych:"All F00–F99 diagnoses pooled, annual, every age and sex — specialist care only.",
    distress:"The source has no age breakdown at all; \"All ages\" is the only option. Renamed from \"Poor mental wellbeing\" — that category stopped being published after 2015-2018.",
    sjukfranvaro:"Real figures cover 2005–2019 only (the source stops there, doesn't extend into the 2020s). No age breakdown."
  },
  realNoteL:"What's actually real here",
  // realNames leads the sentence here (unlike synthPartialB/footBPartial,
  // where it follows a colon) — capitalise just its first letter back up.
  realNoteOn:(n,total,realNames,synthNames,synthN)=>`${realNames.charAt(0).toUpperCase()+realNames.slice(1)} now ${n>1?"run":"runs"} on real, open data, fetched by prototype/pipeline/. Only ${synthNames} ${synthN>1?"have":"has"} no fetcher anywhere in this project and stay${synthN>1?"":"s"} generated — see the label on every chart.`,
  realNoteOff:"No indicator on this page is real data yet. prototype/pipeline/ can fetch real figures for severe anxiety/worry, specialist psychiatric care, self-harm and suicide; run the fetchers, then build_kurvan_data.py, to switch them on.",
  legend:[["survey","The survey","asks people directly"],["reg","The registers","count those who reached care"],["mort","The death register","misses nobody"]],
  kick:"This week's exhibit",
  h1:"The age most likely to self-harm is not the age most likely to die",
  hp:"Self-harm admissions peak before twenty-five and are highest among young women. Suicide mortality climbs across the whole life course and is highest among the oldest men. Nearly all public attention sits on the first curve.",
  twinT:"Two curves, one population",
  shTitle:"Hospitalised for self-harm", suTitle:"Died by suicide",
  perK:"per 100 000 · 2024", women:"women", men:"men",
  peakSh:"women 15–24", peakSu:"men 85+",
  gapTitle:"Reported need against healthcare response",
  gapUnit:"21 regions · adults · 2024 · two independent instruments",
  gapX:"reporting severe anxiety, worry or dread, % (survey)",
  gapY:"antidepressants dispensed, per 1,000 (register)",
  gapLine:"average association between need and response",
  causalNote:"A relationship is not a cause. Regions differ for many reasons this chart does not show.",
  gapPiece:{tag:"Need and response",inst:"reg",h:"Widest distance between need and response",p:"The region with the largest distance between reported need and recorded care response, 2024.",numl:"widest distance, 2024"},
  pieces:[
    {tag:"Life course",inst:"mort",h:"The oldest men",p:"Suicide among men 85+ is the country's highest rate. The survey stops at 84, so the group appears in no measure of self-reported health.",numl:"per 100,000 · men 85+"},
    {tag:"Prescribing",inst:"reg",h:"Young women, 20 years of increase",p:"Antidepressants dispensed to women 15–24 since the register began in 2006.",numl:"2006 → 2024 · women 15–24"}
  ],
  ind:{distress:"Severe anxiety, worry or dread",antidep:"Antidepressants dispensed",psych:"Specialist psychiatric care",selfharm:"Hospitalised for self-harm",suicide:"Died by suicide",sjukfranvaro:"Sickness absence, stress reaction (F43)"},
  fkLead:"Share of ongoing sickness-benefit cases with a stress-reaction (F43) diagnosis — a societal/functional impact measure, not a direct measure of mental health and not a cost estimate.",
  konLead:"Severe anxiety/worry, specialist psychiatric care and sickness absence are all published broken down by sex in their sources — this compares women and men over time for each measure, national figures.",
  konCaveat:"Hospitalised for self-harm and died by suicide aren't here: those sources only publish total sex, no real breakdown by women/men exists to show.",
  lblInd:"Indicator",lblAge:"Age band",lblSex:"Sex",lblYear:"Year",lblReg:"Region",
  allAges:"All ages",sexT:"Total",sexM:"Men",sexK:"Women",
  crude:"Crude",std:"Age-standardised",
  dotTitle:"All 21 regions",dotSub:"Sorted · 95% confidence intervals. Overlapping intervals are not a ranking.",
  ageTitle:"Across the life course",ageSub:"against the national band",
  timeTitle:"Over time",
  natLine:"Sweden",
  winLbl:y=>`${y-2}–${y+2}`,   // y is the window's MIDPOINT (matches midpoint_year everywhere real data is keyed), not its end. No "fönster"/"window" prefix — the dash range already reads as a period, and the Over time tab's own year dropdown shows the same range unprefixed.
  suppLbl:"Withheld, fewer than 10 cases per window:",
  surveyEnd:"the survey stops at 84",
  breakLbl:"measure revised",
  pandemicLbl:"pandemic",
  spreadNote:(s,mode)=>`The spread between the highest and lowest region is <b>${s}%</b> of the national level. ${mode?"Switch to crude and see how much age structure adds.":"Switch to age-standardised and see how much of it is age structure."}`,
  notNum:"What this number is not.",
  notNumB:{
    antidep:"Counts people who collected a prescription, from any prescriber. Not a diagnosis, and it rises when treatment improves as well as when health worsens.",
    psych:"Counts specialist care only. Most ordinary depression is managed in primary care and does not appear here at all.",
    selfharm:"Counts admissions, not people. Y10–Y34 is carried alongside X60–X84 because coding of intent drifts between regions.",
    suicide:"Five-year windows. Counts below 10 per window are withheld; the rate is still published.",
    distress:"Self-reported, ages 16–84. Published in four-year windows (two survey waves pooled for regional reliability); the region table has no age breakdown at all.",
    sjukfranvaro:"Share of ongoing sickness-benefit cases, not a share of the population. Counts sick-leave cases, not people with poor mental health in general — and doesn't measure treatment or diagnosis in healthcare."
  },
  dl:"Download this series",
  peers:"Compared with peer regions (age structure and income):",
  rDistress:"Severe anxiety",rTreated:"Treated",rSuicide:"Suicide",
  vsPeers:"Peers",notDiff:"Difference not distinguishable from zero.",
  higher:"Higher than peers.",lower:"Lower than peers.",
  gapPos:"Where the region sits: need vs. response",gapPosU:"residual from the average association · 2024",
  scatterBelowKey:"Furthest below the average association",scatterAboveKey:"Furthest above the average association",
  behovLead:"Reported need compared with recorded healthcare response, region by region.",
  behovOpen:"Open Need & care →",
  changed:"What moved",changedU:(a,b)=>`${a} → ${b} · change with intervals`,
  withinCI:"within interval",
  chgNote:n=>`<b>${n} of 4 changes are not changes.</b> They sit inside the interval and are shown greyed.`,
  methodH:"How these figures were made",
  mIndicator:"Indicator",mSource:"Source",mFrom:"Series from",mGrain:"Grain",mLimit:"The caveat that matters most",
  mRows:{
    distress:["Region, ~4-year windows","Ages 16–84 only. No age breakdown in the region table; windows are unevenly spaced, not a fixed cadence."],
    antidep:["Region","Register began July 2005; full years from 2006. Dispensing, not diagnosis."],
    psych:["Region","Specialist care only (SVOV definition from 2008). Primary care not included."],
    selfharm:["Region","From 2008. Admissions, not people. Y10–Y34 carried alongside."],
    suicide:["Region, 5-year windows","From 1997 nationally; windows from 2001. Counts <10 withheld."],
    sjukfranvaro:["Region","From 2005, but the source stops in 2019 — doesn't extend into the 2020s. Share of ongoing sickness-benefit cases with diagnosis F43, not a share of the population."]
  },
  mProse:{
    a:"Three instruments, not one",
    b:"The survey asks people directly, the registers count those who reached care, the death register misses nobody. The instruments are blind in different places, which is why the distance between them means something. One concrete example: the survey stops at age 84, and the country's highest suicide rate sits among men 85 and older. The group at greatest risk is invisible to every measure of self-reported health. Sickness absence is added as a fourth, different instrument: a measure of societal impact, not of mental health itself.",
    c:"Age standardisation",
    d:"Regional age structures differ a great deal. A crude figure for anything age-related is largely a map of age structure. Both versions are published, with the toggle visible.",
    e:"Uncertainty and small counts",
    f:"Every regional figure carries its 95% interval. Suicide is reported in five-year windows at region level, and windows with fewer than ten cases are published without a count. The row stays: a missing row reads as missing data, not as a protected one.",
    g:"What these figures cannot tell you",
    h:"The patient register holds specialist care only, so most ordinary depression is missing, and missing unevenly between regions. These are area statistics, not statements about individuals. Incidence cannot be derived from aggregate data."
  },
  mapTitle:"Region map",
  mapNote:(real)=>real
    ?"Colour strength shows the level of the selected indicator. The map is real geography — the values are real Socialstyrelsen data too; see the caveat below."
    :"Colour strength shows the level of the selected indicator, 2024. The map itself is real geography — the values are still synthetic.",
  mapPicked:"selected region",mapOpen:"Open the region page",
  trendWith:"tracking the national trend",trendAgainst:"against the national trend",
  trendNote:(a,b)=>`Hover a region for a ↑/↓/→ arrow: change ${a}→${b} against the interval, and whether it tracks or runs against the national move.`,
  cmpToggle:"⇄ Compare two maps",
  zoomIn:"Zoom in on the map",zoomOut:"Zoom out on the map",
  histTitle:"Distribution across regions",
  histSub:"Number of regions per value band. Shows the spread, not which region is which.",
  histCount:"number of regions",
  helpA:"Självmordslinjen 90101",helpB:"open around the clock, every day",helpC:"1177 for care advice",
  footA:"Draft. Built on the open-data observatory architecture developed for the Swedish Child Health Observatory. A separate project, not affiliated with barnhalsovard.se.",
  footB:"Every figure on this page is generated to show a design. None is a measurement, and none should be quoted. The source references describe where the real series live.",
  footBPartial:(n,total,realNames,synthNames,synthN)=>`${n} of ${total} indicators — ${realNames} — now draw on real, open statistics and can be cited with their respective sources. Only ${synthNames} ${synthN>1?"are":"is"} still generated to show a design; that figure is not a measurement.`
}};
