"use strict";

/* Generated by prototype/pipeline/build_kurvan_data.py. Do not hand-edit.
   Regenerate with:
     python prototype/pipeline/fetch_socialstyrelsen_mh.py
     python prototype/pipeline/fetch_socialstyrelsen_psych.py
     python prototype/pipeline/build_kurvan_data.py

   Empty `rows` on any one of these means that source's fetcher has not
   been run on this machine yet — js/data.js falls back to the labelled-
   synthetic generator for that indicator only, rather than showing
   nothing or fabricating something under a "real data" label. */

/* Real, region-grain rates for self-harm hospitalisation and suicide.
   Fetched by fetch_socialstyrelsen_mh.py. */
const REAL_MH = {"generated_at":"2026-08-25T08:16:07+00:00","source":"Socialstyrelsen Statistikdatabasen (Patientregistret + Dödsorsaksregistret)","rows":[]};

/* Real, region-grain rates for specialist psychiatric care, all nine of
   Kurvan's age bands and all three sexes, annual. Fetched by
   fetch_socialstyrelsen_psych.py. */
const REAL_PSYCH_MH = {"generated_at":"2026-08-25T08:16:07+00:00","source":"Socialstyrelsen Statistikdatabasen (Patientregistret, diagnoserislutenoppenvard, F00-F99)","rows":[]};

/* Real, region-grain shares for self-reported severe anxiety/worry/dread,
   all three sexes, no age breakdown (this table doesn't have one), ~4-year
   survey windows. Fetched by fetch_folkhalsodata_hlv.py — read that
   script's docstring before assuming any other HLV category behaves the
   same way; several stopped being published years ago. */
const REAL_HLV_MH = {"generated_at":"2026-08-25T08:16:07+00:00","source":"Folkhälsomyndigheten Folkhälsodata (Nationella folkhälsoenkäten / HLV, \"Svår ängslan, oro eller ångest\")","rows":[]};

/* Real, region-grain rates for antidepressants dispensed, all nine of
   Kurvan's age bands and all three sexes, annual. Fetched by
   fetch_socialstyrelsen_lakemedel.py. Was assumed to need a multi-
   gigabyte bulk download (the microdata register does) — this is a
   separate, small aggregate table on the same API as the other real
   Socialstyrelsen indicators here. */
const REAL_LAKEMEDEL_MH = {"generated_at":"2026-08-25T08:16:07+00:00","source":"Socialstyrelsen Statistikdatabasen (Läkemedelsregistret, ATC N06A)","rows":[]};

/* Real, county-grain share (%) of ongoing sickness-benefit cases with a
   stress-reaction (F43) diagnosis, all three sexes, annual (averaged from
   monthly), 2005 through the current year. No age breakdown. Fetched by
   fetch_forsakringskassan.py. */
const REAL_FK_MH = {"generated_at":"2026-08-25T08:16:07+00:00","source":"Försäkringskassan (share of ongoing sickness-benefit cases, diagnosis F43)","rows":[]};

/* Real, region-grain context indicators, not mental-health measures — one
   demographic (population density), one socioeconomic (low-education share),
   2023 only. Region figures are an UNWEIGHTED mean of that region's
   municipalities, not population-weighted — a real simplification, not
   hidden (see n_kommuner per row). Fetched by fetch_kolada_context.py. */
const REAL_CONTEXT_MH = {"generated_at":"2026-08-25T08:16:07+00:00","source":"Kolada (population density; share of residents 25-64 with low education)","rows":[]};

/* Real, region-grain MEDIAN DAYS waited for a completed first visit,
   monthly, no age/sex breakdown, from a rolling ~12-month window (not
   deep history). NOT fetched by a script — see
   convert_vantetider_bup.py's docstring: this source has no API, and
   the underlying CSV export needs a human to redo periodically to stay
   current. */
const REAL_BUP_WAIT = {"generated_at":"2026-08-25T08:16:07+00:00","source":"Socialstyrelsen (väntetider barn- och ungdomspsykiatrin — BUP waiting times)","rows":[]};

