# -*- coding: utf-8 -*-
"""Turn the fetched Socialstyrelsen panels into Kurvan's real-data cube(s).

Kurvan (kurvan.html) has no server and no build step of its own — it is a
handful of <script> tags. So instead of a JSON file fetched at runtime (which
CORS blocks when the prototype is opened straight off disk), this writes a
plain JS file that assigns a few constants, loaded the same way as every
other file in js/.

Reads:  ../data/processed/socialstyrelsen_mh.json     (fetch_socialstyrelsen_mh.py)
        ../data/processed/socialstyrelsen_psych.json  (fetch_socialstyrelsen_psych.py)
Writes: ../js/real_mh_data.js  (REAL_MH and REAL_PSYCH_MH)

Run:  python prototype/pipeline/build_kurvan_data.py

Either processed file may be missing — each becomes an empty row list rather
than blocking the other. js/data.js checks each row count independently and
falls back to the labelled-synthetic generator per indicator, not per file:
run only fetch_socialstyrelsen_mh.py and self-harm/suicide go real while
psych stays synthetic, or vice versa.
"""
import json
import os
from datetime import datetime, timezone

HERE = os.path.dirname(__file__)
PROCESSED = os.path.join(HERE, "..", "data", "processed")
OUT = os.path.join(HERE, "..", "js", "real_mh_data.js")

SOURCES = [
    {
        "var": "REAL_MH",
        "file": "socialstyrelsen_mh.json",
        "source": "Socialstyrelsen Statistikdatabasen (Patientregistret + Dödsorsaksregistret)",
        "note": "Real, region-grain rates for self-harm hospitalisation and suicide.\n"
                "   Fetched by fetch_socialstyrelsen_mh.py.",
    },
    {
        "var": "REAL_PSYCH_MH",
        "file": "socialstyrelsen_psych.json",
        "source": "Socialstyrelsen Statistikdatabasen (Patientregistret, diagnoserislutenoppenvard, F00-F99)",
        "note": "Real, region-grain rates for specialist psychiatric care, all nine of\n"
                "   Kurvan's age bands and all three sexes, annual. Fetched by\n"
                "   fetch_socialstyrelsen_psych.py.",
    },
    {
        "var": "REAL_HLV_MH",
        "file": "folkhalsodata_hlv.json",
        "source": "Folkhälsomyndigheten Folkhälsodata (Nationella folkhälsoenkäten / HLV, "
                  "\"Svår ängslan, oro eller ångest\")",
        "note": "Real, region-grain shares for self-reported severe anxiety/worry/dread,\n"
                "   all three sexes, no age breakdown (this table doesn't have one), ~4-year\n"
                "   survey windows. Fetched by fetch_folkhalsodata_hlv.py — read that\n"
                "   script's docstring before assuming any other HLV category behaves the\n"
                "   same way; several stopped being published years ago.",
    },
    {
        "var": "REAL_FK_MH",
        "file": "forsakringskassan_f43.json",
        "source": "Försäkringskassan (share of ongoing sickness-benefit cases, diagnosis F43)",
        "note": "Real, county-grain share (%) of ongoing sickness-benefit cases with a\n"
                "   stress-reaction (F43) diagnosis, all three sexes, annual (averaged from\n"
                "   quarterly), 2005-2019 only — this source does not extend into the 2020s.\n"
                "   No age breakdown. Fetched by fetch_forsakringskassan.py.",
    },
    {
        "var": "REAL_CONTEXT_MH",
        "file": "kolada_context.json",
        "source": "Kolada (population density; share of residents 25-64 with low education)",
        "note": "Real, region-grain context indicators, not mental-health measures — one\n"
                "   demographic (population density), one socioeconomic (low-education share),\n"
                "   2023 only. Region figures are an UNWEIGHTED mean of that region's\n"
                "   municipalities, not population-weighted — a real simplification, not\n"
                "   hidden (see n_kommuner per row). Fetched by fetch_kolada_context.py.",
    },
]


def load(filename):
    path = os.path.join(PROCESSED, filename)
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            rows = json.load(f)
        print(f"[build_kurvan_data] read {len(rows)} rows from {path}")
        return rows
    print(f"[build_kurvan_data] {path} not found — this source stays empty "
          f"(its indicator(s) fall back to the labelled-synthetic generator).")
    return []


def main():
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write('"use strict";\n\n')
        f.write("/* Generated by prototype/pipeline/build_kurvan_data.py. Do not hand-edit.\n")
        f.write("   Regenerate with:\n")
        f.write("     python prototype/pipeline/fetch_socialstyrelsen_mh.py\n")
        f.write("     python prototype/pipeline/fetch_socialstyrelsen_psych.py\n")
        f.write("     python prototype/pipeline/build_kurvan_data.py\n\n")
        f.write("   Empty `rows` on any one of these means that source's fetcher has not\n")
        f.write("   been run on this machine yet — js/data.js falls back to the labelled-\n")
        f.write("   synthetic generator for that indicator only, rather than showing\n")
        f.write("   nothing or fabricating something under a \"real data\" label. */\n\n")
        for spec in SOURCES:
            rows = load(spec["file"])
            payload = {"generated_at": now, "source": spec["source"], "rows": rows}
            f.write(f"/* {spec['note']} */\n")
            f.write(f"const {spec['var']} = ")
            # Compact, not indent=1: this file is loaded as a blocking
            # <script> on every page load (see the module docstring above
            # for why it can't be a fetch()ed JSON file instead), so its
            # size is pure page-weight — pretty-printing ~16,000 rows added
            # a quarter more bytes for zero benefit, since nobody reads this
            # file (the "Do not hand-edit" note above is the whole point).
            f.write(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
            f.write(";\n\n")

    print(f"[build_kurvan_data] wrote {OUT}")
    print("[build_kurvan_data] reopen kurvan.html to see the result.")


if __name__ == "__main__":
    main()
